### ISSUE TITLE
ghc 8.10.1

### ISSUE THREAD

**Issue by simonmichael** [DanBurton/stack-setup-info-gen#8]
Hi @DanBurton, could we possibly have a new file for the official GHC 8.10.1 release ? Thanks for these, very handy.

**Comment by DanBurton** [comment]
`stack setup ghc-8.10.1` should already work out of the box. But since it's easy to do, I went ahead and generated the file anyway (https://github.com/DanBurton/stack-setup-info-gen/commit/5855d3d70e5a0e503397ac1d045e6db5df503a79) . Are you using it for something other than `stack setup`?

**Comment by simonmichael** [comment]
Ah, good point. stack setup would work fine for me as well. Thanks.

**Comment by DanBurton** [comment]
Oh I'm not entirely sure this file is useable as is, it looks like there are now `.tar.lz` and `.tar.xz` downloads for all platforms. I'll filter out the `lz`s for now and update the file.

**Comment by simonmichael** [comment]
And actually stack setup just installs ghc, right ? I'm not sure how to generate a stack.yaml with stack any more.

**Comment by simonmichael** [comment]
Though, I guess with a released ghc it can be as simple as:
```
resolver: ghc-8.10.1
packages: ...
```
Ie, I don't need to specify all that setup-info ?

**Comment by DanBurton** [comment]
Yes that's correct.
