### ISSUE TITLE
ghc 9.0.1 final is released

### ISSUE THREAD

**Issue by simonmichael** [DanBurton/stack-setup-info-gen#9]
stack-ghc-9.0.1-alpha1.yaml could use an update ? Thanks!

**Comment by DanBurton** [comment]
ghc 9.0.1-alpha1 is a different (older) release than ghc 9.0.1. The output files for the old one won't be "updated" because they are still accurate for that particular alpha1 version. Are you asking for _additional_ output files for ghc 9.0.1? I can do that if they are useful to you.

**Comment by simonmichael** [comment]
Yes that's what I meant. I thought the policy was a stack yaml file for each new ghc release.

**Comment by DanBurton** [comment]
I typically use these files for installing alpha and rc versions of ghc. If you are using these files for info on proper release versions, you might also be interested in https://github.com/commercialhaskell/stackage-content/blob/master/stack/stack-setup-2.yaml which is the file stack uses by default.

**Comment by simonmichael** [comment]
Oh I see. I'll look into that, thanks Dan!

**Comment by DanBurton** [comment]
Added file in 3aef6a0021278c77f780339bb70a3b9e585fa599
